project_id = "geoqbbrlyepmhwgdbjmz"

[auth]
site_url = "https://socialhub-pro-1.onrender.com"
additional_redirect_urls = ["https://socialhub-pro-1.onrender.com/auth/callback"]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[storage.vector]
enabled = false
