-- GERADO POR scripts/generate-layout-seed.cjs — não editar à mão.
-- Catálogo interno (§8). `is_builtin` marca o que veio da biblioteca do produto;
-- o administrador pode desativar uma linha mudando `status`, sem perder a origem.

INSERT INTO public.layout_structures (id, name, category, format, width, height, slides, status, structure, is_builtin) VALUES
  ('imagem-titulo', 'Imagem com título sobreposto', 'visual', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Imagem em tela cheia, título sobre a imagem, subtítulo e logo.","density":"airy","shapes":["square","story"],"requires":{"image":true},"uses":{"image":true,"bullets":false,"subtext":true,"cta":false,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["noticia","inspiracao","promocao"],"slots":[{"component":"imagem-principal","bleed":true,"x":0,"y":0,"w":1,"h":1},{"component":"sobreposicao","bleed":true,"x":0,"y":0.42,"w":1,"h":0.58},{"component":"selo-categoria","x":0,"y":0,"w":0.42,"h":0.05},{"component":"titulo","x":0,"y":0.55,"w":1,"h":0.24},{"component":"subtitulo","x":0,"y":0.81,"w":0.92,"h":0.1},{"component":"logo","x":0,"y":0.94,"w":0.6,"h":0.05}]}'::jsonb, TRUE),
  ('titulo-imagem-texto', 'Título, imagem e texto', 'informativo', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Título no topo, imagem central, texto na parte inferior e rodapé.","density":"normal","shapes":["square","story"],"requires":{"image":true,"subtext":true},"uses":{"image":true,"bullets":false,"subtext":true,"cta":false,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["noticia","educativo","inspiracao"],"slots":[{"component":"selo-categoria","x":0,"y":0,"w":0.4,"h":0.05},{"component":"titulo","x":0,"y":0.07,"w":1,"h":0.2},{"component":"imagem-principal","x":0,"y":0.3,"w":1,"h":0.38},{"component":"subtitulo","x":0,"y":0.71,"w":1,"h":0.16},{"component":"divisor","x":0,"y":0.9,"w":0.22,"h":0.008},{"component":"logo","x":0,"y":0.94,"w":0.6,"h":0.05}]}'::jsonb, TRUE),
  ('editorial', 'Editorial', 'editorial', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Título grande, texto curto, imagem e bloco de destaque com rodapé.","density":"normal","shapes":["square","story"],"requires":{"image":true,"subtext":true},"uses":{"image":true,"bullets":false,"subtext":true,"cta":false,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["educativo","autoridade","noticia"],"slots":[{"component":"titulo","x":0,"y":0,"w":1,"h":0.22},{"component":"subtitulo","x":0,"y":0.24,"w":0.88,"h":0.12},{"component":"imagem-principal","x":0,"y":0.39,"w":1,"h":0.34},{"component":"box-informativo","x":0,"y":0.76,"w":1,"h":0.12},{"component":"logo","x":0,"y":0.94,"w":0.55,"h":0.05},{"component":"data","x":0.62,"y":0.94,"w":0.38,"h":0.05}]}'::jsonb, TRUE),
  ('conteudo-limpo', 'Conteúdo limpo', 'informativo', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Fundo simples, título, texto, imagem pequena e CTA.","density":"airy","shapes":["square","story"],"requires":{},"uses":{"image":true,"bullets":false,"subtext":true,"cta":true,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["educativo","autoridade","servico"],"slots":[{"component":"selo-categoria","x":0,"y":0,"w":0.4,"h":0.05},{"component":"titulo","x":0,"y":0.09,"w":1,"h":0.24},{"component":"subtitulo","x":0,"y":0.36,"w":0.9,"h":0.16},{"component":"imagem-principal","x":0,"y":0.56,"w":0.46,"h":0.26},{"component":"cta","x":0,"y":0.87,"w":0.5,"h":0.06},{"component":"logo","x":0.58,"y":0.87,"w":0.42,"h":0.06}]}'::jsonb, TRUE),
  ('manchete', 'Manchete', 'noticia', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Selo, título grande e linha de apoio ancorada embaixo.","density":"normal","shapes":["square","story"],"requires":{},"uses":{"image":false,"bullets":false,"subtext":true,"cta":false,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["noticia","autoridade"],"slots":[{"component":"painel","bleed":true,"x":0,"y":0,"w":1,"h":1},{"component":"selo-categoria","x":0,"y":0.02,"w":0.44,"h":0.055},{"component":"divisor","x":0,"y":0.11,"w":0.3,"h":0.01},{"component":"titulo","x":0,"y":0.16,"w":1,"h":0.4},{"component":"box-informativo","x":0,"y":0.62,"w":1,"h":0.18},{"component":"logo","x":0,"y":0.93,"w":0.55,"h":0.05},{"component":"data","x":0.62,"y":0.93,"w":0.38,"h":0.05}]}'::jsonb, TRUE),
  ('citacao', 'Citação', 'engajamento', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Painel de marca com uma frase forte e a assinatura.","density":"airy","shapes":["square","story"],"requires":{"fields":["quote"]},"uses":{"image":false,"bullets":false,"subtext":true,"cta":false,"warning":false,"quote":true,"stat":false,"question":false},"contentTypes":["inspiracao","autoridade"],"slots":[{"component":"painel","x":0,"y":0.06,"w":1,"h":0.7},{"component":"citacao","x":0.06,"y":0.14,"w":0.88,"h":0.44},{"component":"subtitulo","x":0.06,"y":0.6,"w":0.88,"h":0.1},{"component":"logo","x":0,"y":0.86,"w":0.6,"h":0.05}]}'::jsonb, TRUE),
  ('estatistica', 'Estatística', 'autoridade', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Número grande em destaque com a leitura do dado.","density":"airy","shapes":["square","story"],"requires":{"fields":["stat"]},"uses":{"image":false,"bullets":false,"subtext":true,"cta":true,"warning":false,"quote":false,"stat":true,"question":false},"contentTypes":["dado","autoridade","noticia"],"slots":[{"component":"selo-categoria","x":0,"y":0,"w":0.42,"h":0.05},{"component":"estatistica","x":0,"y":0.12,"w":1,"h":0.3},{"component":"estatistica-legenda","x":0,"y":0.45,"w":0.92,"h":0.16},{"component":"divisor","x":0,"y":0.65,"w":0.26,"h":0.01},{"component":"subtitulo","x":0,"y":0.7,"w":0.92,"h":0.12},{"component":"cta","x":0,"y":0.88,"w":0.5,"h":0.06},{"component":"logo","x":0.58,"y":0.88,"w":0.42,"h":0.06}]}'::jsonb, TRUE),
  ('lista', 'Lista', 'educativo', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Título e itens numerados, com chamada no rodapé.","density":"dense","shapes":["square","story"],"requires":{"minBullets":3},"uses":{"image":false,"bullets":true,"subtext":false,"cta":true,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["educativo","servico"],"slots":[{"component":"selo-categoria","x":0,"y":0,"w":0.42,"h":0.05},{"component":"titulo","x":0,"y":0.08,"w":1,"h":0.17},{"component":"lista","index":0,"x":0,"y":0.29,"w":1,"h":0.13},{"component":"lista","index":1,"x":0,"y":0.44,"w":1,"h":0.13},{"component":"lista","index":2,"x":0,"y":0.59,"w":1,"h":0.13},{"component":"lista","index":3,"x":0,"y":0.74,"w":1,"h":0.13,"optional":true},{"component":"cta","x":0,"y":0.9,"w":0.5,"h":0.06},{"component":"logo","x":0.58,"y":0.9,"w":0.42,"h":0.06}]}'::jsonb, TRUE),
  ('comparativo', 'Comparativo', 'educativo', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Dois lados lado a lado, para antes e depois.","density":"normal","shapes":["square","story"],"requires":{"minBullets":2,"maxBullets":2},"uses":{"image":false,"bullets":true,"subtext":false,"cta":false,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["educativo","dado"],"slots":[{"component":"titulo","x":0,"y":0,"w":1,"h":0.2},{"component":"comparacao","index":0,"x":0,"y":0.26,"w":0.47,"h":0.42},{"component":"comparacao","index":1,"x":0.53,"y":0.26,"w":0.47,"h":0.42},{"component":"destaque-palavra","x":0.36,"y":0.72,"w":0.28,"h":0.08},{"component":"logo","x":0,"y":0.93,"w":0.6,"h":0.05}]}'::jsonb, TRUE),
  ('pergunta', 'Pergunta', 'engajamento', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Pergunta grande para abrir conversa, com chamada de resposta.","density":"airy","shapes":["square","story"],"requires":{"fields":["question"]},"uses":{"image":false,"bullets":false,"subtext":true,"cta":true,"warning":false,"quote":false,"stat":false,"question":true},"contentTypes":["engajamento","educativo"],"slots":[{"component":"selo-categoria","x":0,"y":0,"w":0.44,"h":0.05},{"component":"pergunta","x":0,"y":0.16,"w":1,"h":0.36},{"component":"subtitulo","x":0,"y":0.56,"w":0.9,"h":0.12},{"component":"cta","x":0,"y":0.82,"w":0.56,"h":0.07},{"component":"logo","x":0,"y":0.93,"w":0.6,"h":0.05}]}'::jsonb, TRUE),
  ('capa-carrossel', 'Capa de carrossel', 'carrossel', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Capa com selo, título, contagem de slides e assinatura.","density":"normal","shapes":["square","story"],"requires":{},"uses":{"image":true,"bullets":false,"subtext":true,"cta":false,"warning":false,"quote":false,"stat":false,"question":false},"contentTypes":["educativo","autoridade","noticia"],"slots":[{"component":"imagem-principal","bleed":true,"x":0,"y":0,"w":1,"h":1},{"component":"sobreposicao","bleed":true,"x":0,"y":0,"w":1,"h":1},{"component":"selo-categoria","x":0,"y":0.02,"w":0.44,"h":0.055},{"component":"titulo","x":0,"y":0.28,"w":1,"h":0.32},{"component":"subtitulo","x":0,"y":0.63,"w":0.9,"h":0.12},{"component":"logo","x":0,"y":0.93,"w":0.55,"h":0.05},{"component":"numero-slide","x":0.7,"y":0.93,"w":0.3,"h":0.05}]}'::jsonb, TRUE),
  ('aviso', 'Aviso', 'servico', 'todos', 1080, 1080, 1, 'ativo', '{"description":"Box de alerta com o recado e a ação esperada.","density":"normal","shapes":["square","story"],"requires":{"fields":["warning"]},"uses":{"image":false,"bullets":false,"subtext":true,"cta":true,"warning":true,"quote":false,"stat":false,"question":false},"contentTypes":["servico","promocao","noticia"],"slots":[{"component":"selo-categoria","x":0,"y":0,"w":0.44,"h":0.055},{"component":"titulo","x":0,"y":0.1,"w":1,"h":0.22},{"component":"aviso","x":0,"y":0.36,"w":1,"h":0.22},{"component":"subtitulo","x":0,"y":0.62,"w":0.92,"h":0.14},{"component":"cta","x":0,"y":0.85,"w":0.54,"h":0.07},{"component":"logo","x":0,"y":0.94,"w":0.6,"h":0.05}]}'::jsonb, TRUE)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, structure = EXCLUDED.structure, updated_at = NOW();

INSERT INTO public.layout_components (id, name, type, behavior, text_limits, default_position, default_style, properties, is_builtin) VALUES
  ('titulo', 'Título', 'text', 'dynamic', '{"min":3,"max":90}'::jsonb, '{"styleRole":"title","safeMarginFactor":1}'::jsonb, '{"weight":800,"align":"left","lh":1.05,"fill":"transparent"}'::jsonb, '{"field":"title","required":true,"index":false}'::jsonb, TRUE),
  ('subtitulo', 'Subtítulo', 'text', 'dynamic', '{"max":160}'::jsonb, '{"styleRole":"subtitle","safeMarginFactor":1}'::jsonb, '{"weight":400,"align":"left","lh":1.28,"fill":"transparent"}'::jsonb, '{"field":"subtitle","required":false,"index":false}'::jsonb, TRUE),
  ('imagem-principal', 'Imagem principal', 'media', 'dynamic', '{}'::jsonb, '{"styleRole":null,"safeMarginFactor":1}'::jsonb, '{}'::jsonb, '{"field":"imageUrl","required":false,"index":false}'::jsonb, TRUE),
  ('selo-categoria', 'Selo de categoria', 'button', 'dynamic', '{"max":24}'::jsonb, '{"styleRole":"eyebrow","safeMarginFactor":1}'::jsonb, '{"weight":700,"align":"center","tt":"upper","ls":1,"radius":999}'::jsonb, '{"field":"eyebrow","required":false,"index":false}'::jsonb, TRUE),
  ('logo', 'Logo', 'text', 'dynamic', '{"max":32}'::jsonb, '{"styleRole":"meta","safeMarginFactor":1.4}'::jsonb, '{"weight":700,"align":"left","fill":"transparent"}'::jsonb, '{"field":"brand","required":false,"index":false}'::jsonb, TRUE),
  ('cta', 'CTA', 'button', 'dynamic', '{"max":32}'::jsonb, '{"styleRole":"cta","safeMarginFactor":1}'::jsonb, '{"weight":700,"align":"center","radius":999}'::jsonb, '{"field":"cta","required":false,"index":false}'::jsonb, TRUE),
  ('numero-slide', 'Número do slide', 'text', 'dynamic', '{"max":6}'::jsonb, '{"styleRole":"meta","safeMarginFactor":1}'::jsonb, '{"weight":700,"align":"right","fill":"transparent"}'::jsonb, '{"field":"slideNumber","required":false,"index":false}'::jsonb, TRUE),
  ('rodape', 'Rodapé', 'text', 'dynamic', '{"max":60}'::jsonb, '{"styleRole":"meta","safeMarginFactor":1}'::jsonb, '{"weight":400,"align":"left","fill":"transparent"}'::jsonb, '{"field":"footer","required":false,"index":false}'::jsonb, TRUE),
  ('citacao', 'Bloco de citação', 'text', 'dynamic', '{"max":140}'::jsonb, '{"styleRole":"title","safeMarginFactor":1}'::jsonb, '{"weight":700,"align":"left","italic":true,"lh":1.18,"fill":"transparent"}'::jsonb, '{"field":"quote","required":false,"index":false}'::jsonb, TRUE),
  ('destaque-palavra', 'Destaque de palavra', 'text', 'dynamic', '{"max":28}'::jsonb, '{"styleRole":"subtitle","safeMarginFactor":1}'::jsonb, '{"weight":800,"align":"center","tt":"upper","bgMode":"box","bgRadius":8,"fill":"transparent"}'::jsonb, '{"field":"highlight","required":false,"index":false}'::jsonb, TRUE),
  ('estatistica', 'Bloco de estatística', 'text', 'dynamic', '{"max":10}'::jsonb, '{"styleRole":"number","safeMarginFactor":1}'::jsonb, '{"weight":800,"align":"left","lh":1,"fill":"transparent"}'::jsonb, '{"field":"stat","required":false,"index":false}'::jsonb, TRUE),
  ('estatistica-legenda', 'Legenda da estatística', 'text', 'dynamic', '{"max":90}'::jsonb, '{"styleRole":"body","safeMarginFactor":1}'::jsonb, '{"weight":400,"align":"left","lh":1.25,"fill":"transparent"}'::jsonb, '{"field":"statLabel","required":false,"index":false}'::jsonb, TRUE),
  ('comparacao', 'Comparação', 'text', 'dynamic', '{"max":70}'::jsonb, '{"styleRole":"body","safeMarginFactor":1}'::jsonb, '{"weight":600,"align":"left","lh":1.25,"radius":14}'::jsonb, '{"field":"bullets","required":false,"index":true}'::jsonb, TRUE),
  ('lista', 'Lista', 'text', 'dynamic', '{"max":70}'::jsonb, '{"styleRole":"body","safeMarginFactor":1}'::jsonb, '{"weight":600,"align":"left","lh":1.25,"fill":"transparent"}'::jsonb, '{"field":"bullets","required":false,"index":true}'::jsonb, TRUE),
  ('aviso', 'Aviso', 'text', 'dynamic', '{"max":120}'::jsonb, '{"styleRole":"body","safeMarginFactor":1}'::jsonb, '{"weight":600,"align":"left","lh":1.25,"radius":12}'::jsonb, '{"field":"warning","required":false,"index":false}'::jsonb, TRUE),
  ('pergunta', 'Pergunta', 'text', 'dynamic', '{"max":90}'::jsonb, '{"styleRole":"title","safeMarginFactor":1}'::jsonb, '{"weight":800,"align":"left","lh":1.08,"fill":"transparent"}'::jsonb, '{"field":"question","required":false,"index":false}'::jsonb, TRUE),
  ('box-informativo', 'Box informativo', 'text', 'dynamic', '{"max":180}'::jsonb, '{"styleRole":"body","safeMarginFactor":1}'::jsonb, '{"weight":400,"align":"left","lh":1.3,"radius":16}'::jsonb, '{"field":"info","required":false,"index":false}'::jsonb, TRUE),
  ('painel', 'Painel de fundo', 'shape', 'fixed', '{}'::jsonb, '{"styleRole":null,"safeMarginFactor":1}'::jsonb, '{"shape":"rect","text":"","radius":20}'::jsonb, '{"field":null,"required":false,"index":false}'::jsonb, TRUE),
  ('sobreposicao', 'Sobreposição', 'shape', 'fixed', '{}'::jsonb, '{"styleRole":null,"safeMarginFactor":1}'::jsonb, '{"shape":"rect","text":"","radius":0,"op":0.55,"fill":"#000000"}'::jsonb, '{"field":null,"required":false,"index":false}'::jsonb, TRUE),
  ('divisor', 'Divisor', 'line', 'fixed', '{}'::jsonb, '{"styleRole":null,"safeMarginFactor":1}'::jsonb, '{"dash":"solid","cap":"round","text":""}'::jsonb, '{"field":null,"required":false,"index":false}'::jsonb, TRUE),
  ('data', 'Data', 'text', 'dynamic', '{"max":24}'::jsonb, '{"styleRole":"meta","safeMarginFactor":1}'::jsonb, '{"weight":600,"align":"right","fill":"transparent"}'::jsonb, '{"field":"date","required":false,"index":false}'::jsonb, TRUE)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, text_limits = EXCLUDED.text_limits, default_style = EXCLUDED.default_style, updated_at = NOW();

INSERT INTO public.visual_styles (id, name, rules, typography, spacing, contrast, image_config, effects, is_builtin) VALUES
  ('editorial', 'Editorial', '{"intensity":"media","highlight":"underline","radius":4,"keywords":["editorial","revista","artigo","ensaio","moda","arquitetura","interiores","design"]}'::jsonb, '{"fonts":{"title":"Playfair Display","body":"Lora","accent":"Playfair Display"},"typeScale":{"title":1.06,"subtitle":1.04},"titleWeight":700,"letterSpacing":{"eyebrow":2,"title":0},"uppercaseEyebrow":false}'::jsonb, '{"factor":1.15}'::jsonb, 'alto', '{"mode":"framed"}'::jsonb, '{"shadow":false}'::jsonb, TRUE),
  ('jornalistico', 'Jornalístico', '{"intensity":"alta","highlight":"box","radius":0,"keywords":["noticia","notícia","jornal","urgente","manchete","imprensa","politica","política","economia"]}'::jsonb, '{"fonts":{"title":"Archivo Black","body":"Montserrat","accent":"Montserrat"},"typeScale":{"title":1.12,"subtitle":0.96},"titleWeight":400,"letterSpacing":{"eyebrow":2,"title":-0.5},"uppercaseEyebrow":true}'::jsonb, '{"factor":0.9}'::jsonb, 'maximo', '{"mode":"full"}'::jsonb, '{"shadow":false}'::jsonb, TRUE),
  ('tecnologia', 'Tecnologia', '{"intensity":"alta","highlight":"color","radius":18,"keywords":["tecnologia","tech","software","app","startup","saas","ti","digital","ia","dados","marketing digital"]}'::jsonb, '{"fonts":{"title":"Poppins","body":"JetBrains Mono","accent":"Poppins"},"typeScale":{"title":1,"subtitle":0.96},"titleWeight":700,"letterSpacing":{"eyebrow":2,"title":-0.5},"uppercaseEyebrow":true}'::jsonb, '{"factor":1}'::jsonb, 'alto', '{"mode":"framed"}'::jsonb, '{"shadow":true}'::jsonb, TRUE),
  ('minimalista', 'Minimalista', '{"intensity":"baixa","highlight":"none","radius":10,"keywords":["minimalista","clean","simples","essencial","zen","bem-estar"]}'::jsonb, '{"fonts":{"title":"Montserrat","body":"Montserrat","accent":"Montserrat"},"typeScale":{"title":0.94,"subtitle":0.94},"titleWeight":700,"letterSpacing":{"eyebrow":3,"title":-0.3},"uppercaseEyebrow":true}'::jsonb, '{"factor":1.35}'::jsonb, 'medio', '{"mode":"accent"}'::jsonb, '{"shadow":false}'::jsonb, TRUE),
  ('corporativo', 'Corporativo', '{"intensity":"media","highlight":"box","radius":12,"keywords":["corporativo","empresa","b2b","consultoria","contabil","contábil","contabilidade","financeiro","seguros","rh"]}'::jsonb, '{"fonts":{"title":"Poppins","body":"Poppins","accent":"Poppins"},"typeScale":{"title":0.98,"subtitle":1},"titleWeight":700,"letterSpacing":{"eyebrow":2,"title":0},"uppercaseEyebrow":true}'::jsonb, '{"factor":1.05}'::jsonb, 'alto', '{"mode":"framed"}'::jsonb, '{"shadow":false}'::jsonb, TRUE),
  ('premium', 'Premium', '{"intensity":"media","highlight":"underline","radius":2,"keywords":["premium","luxo","advocacia","advogado","juridico","jurídico","direito","joalheria","alto padrao","alto padrão","imobiliaria","imobiliária"]}'::jsonb, '{"fonts":{"title":"Cormorant Garamond","body":"Marcellus","accent":"Marcellus"},"typeScale":{"title":1.14,"subtitle":1},"titleWeight":700,"letterSpacing":{"eyebrow":4,"title":0.5},"uppercaseEyebrow":true}'::jsonb, '{"factor":1.25}'::jsonb, 'alto', '{"mode":"full"}'::jsonb, '{"shadow":true}'::jsonb, TRUE),
  ('acolhedor', 'Acolhedor', '{"intensity":"media","highlight":"box","radius":24,"keywords":["saude","saúde","clinica","clínica","psicologia","infantil","pet","cafe","café","padaria","terapia","nutricao","nutrição","odonto","dentista"]}'::jsonb, '{"fonts":{"title":"Baloo 2","body":"Poppins","accent":"Caveat"},"typeScale":{"title":1,"subtitle":1.02},"titleWeight":700,"letterSpacing":{"eyebrow":1,"title":0},"uppercaseEyebrow":false}'::jsonb, '{"factor":1.2}'::jsonb, 'medio', '{"mode":"framed"}'::jsonb, '{"shadow":true}'::jsonb, TRUE),
  ('comercial', 'Comercial', '{"intensity":"alta","highlight":"box","radius":8,"keywords":["promocao","promoção","oferta","desconto","venda","loja","varejo","ecommerce","e-commerce","delivery","restaurante","black friday"]}'::jsonb, '{"fonts":{"title":"Anton","body":"Montserrat","accent":"Montserrat"},"typeScale":{"title":1.1,"subtitle":0.94},"titleWeight":400,"letterSpacing":{"eyebrow":1.5,"title":0},"uppercaseEyebrow":true}'::jsonb, '{"factor":0.85}'::jsonb, 'maximo', '{"mode":"full"}'::jsonb, '{"shadow":true}'::jsonb, TRUE)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, rules = EXCLUDED.rules, typography = EXCLUDED.typography, updated_at = NOW();

